project_name: EmbryoVision2.0
experiment_name: object_detection
track_in_clearml: true
trainer_config:
  min_epochs: 7
  max_epochs: 13
  check_val_every_n_epoch: 2
  log_every_n_steps: 30
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: false
  fast_dev_run: false
  default_root_dir: null
  detect_anomaly: false
data_config:
  img_size:
  - 224
  - 224
  batch_size: 32
  train_size: 0.8
  num_workers: 8
  pin_memory: true
  num_samples: 11000
module_config:
  model_name: efficientnet_b5
  pretrained: true
  model_kwargs:
    drop_rate: 0.4
  binarization_threshold: 0.5
  optimizer:
    target_class: torch.optim.AdamW
    kwargs:
      lr: 1e-3
      weight_decay: 1e-5
